[package]
name = "base64_rs"
version = "0.0.1"
edition = "2021"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true

[dependencies]
base64 = "0.21.5"

[dependencies.utils]
path = "../../common/rust"
